### PR TITLE
add deployment strategy

### PR DESCRIPTION
**Pull request by vbehar**
so that we can configure a recreate strategy when the persistence is enabled

### CODE REVIEW

**Review by kolesnikovae — COMMENTED** [review]
A very good point. I would even force it.

**Comment by vbehar** [comment]
> A very good point. I would even force it.

you mean that you would prefer to have the `Recreate` strategy by default, in the `values.yaml`?

**Comment by kolesnikovae** [comment]
> > A very good point. I would even force it.
> 
> you mean that you would prefer to have the `Recreate` strategy by default, in the `values.yaml`?

Yes, to my mind it might come in handy.

**Comment by kolesnikovae** [comment]
Awesome work @vbehar, thank you! 🔥

**Pull request merged**
