### PR TITLE
fix: pod annotations

### PR DESCRIPTION
**Pull request by vbehar**
previously, adding pod annotations was breaking the template

### CODE REVIEW

**Comment by kolesnikovae** [comment]
Thank you @vbehar! LGTM

**Comment by vbehar** [comment]
> Thank you @vbehar! LGTM. Please bump chart version.

ok done

**Comment by kolesnikovae** [comment]
> ok done

And docs :)

**Comment by kolesnikovae** [comment]
Could you also please rebase PR – I had to [fix](https://github.com/pyroscope-io/helm-chart/pull/7) CI.

**Review by kolesnikovae — APPROVED** [review]

**Pull request merged**
